## Introduction to Matrices

Sample Matrix (2 Rows and 4 Columns)

## Creating the Matrix using Python

In [12]:
# Matrix with 2 rows and 4 columns
A = [[1, 9, 7, 3],[-4, 6, 12, 1]]

In [13]:
print(A)

[[1, 9, 7, 3], [-4, 6, 12, 1]]


## Creating the Matrix using NumPy

In [14]:
import numpy as np
A = np.array([[1, 9, 7, 3], [-4, 6, 12, 1]])

### Printing the Array

In [16]:
print(A)

[[ 1  9  7  3]
 [-4  6 12  1]]


### Display Dimensions

ndim - It returns the number of array dimensions

In [17]:
print(A.ndim)

2


### Display Shape   

shape - It returns a tuple consisting of array dimensions. It can also be used to resize the array

In [23]:
print(A.shape)

(2, 4)


### Display total number of elements   

size - It returns the total number of elements inside the array

In [24]:
print(A.size)

8


### Display length    

len - It returns length of the array. For ndimension it returns the size of the first dimension

In [21]:
print(len(A))

2


### Display data type  

dtype - It return the data type of the array

In [27]:
print(A.dtype)

int32


## Assignment 1

## Identify the order and total  elements of Matrix

### Problem 1

In [48]:
A = np.array([[2, 10], [9, 7]])

In [49]:
print(A)
print("The shape of the Matrix A is",A.shape)
print("Total number of elements in Matrix A is",A.size)

[[ 2 10]
 [ 9  7]]
The shape of the Matrix A is (2, 2)
Total number of elements in Matrix A is 4


### Problem 2

In [50]:
B = np.array([[2, 4, 7, 1], [9, 10, 0, 8]])

In [51]:
print(B)
print("The shape of the Matrix B is",B.shape)
print("Total number of elements in Matrix B is",B.size)

[[ 2  4  7  1]
 [ 9 10  0  8]]
The shape of the Matrix B is (2, 4)
Total number of elements in Matrix B is 8


### Problem 3

In [52]:
C = np.array([[1, 5, 7, 9], [9, 0, 10, 0], [1, 1, 11, 32], [6, 5, 3, 32], [6, 5, 3, 9]])

In [53]:
print(C)
print("The shape of the Matrix C is",C.shape)
print("Total number of elements in Matrix C is",C.size)

[[ 1  5  7  9]
 [ 9  0 10  0]
 [ 1  1 11 32]
 [ 6  5  3 32]
 [ 6  5  3  9]]
The shape of the Matrix C is (5, 4)
Total number of elements in Matrix C is 20
