## Types of Matrices

### Zero Matrix

In [7]:
import numpy as np
a = np.zeros(3) 
print(a)

[0. 0. 0.]


### Identity Matrix

In [8]:
a = np.ones(3) 
print(a)

[1. 1. 1.]


### Scalar Matrix

In [11]:
a = np.zeros((3, 3), int)
np.fill_diagonal(a, 2)
print(a)

[[2 0 0]
 [0 2 0]
 [0 0 2]]


### Diagonal Matrix

In [14]:
a = np.zeros((3, 3), int)
np.fill_diagonal(a, [1, 10, 7])
print(a)

[[ 1  0  0]
 [ 0 10  0]
 [ 0  0  7]]


Extract the Diagonal Values

In [16]:
np.diag(a)

array([ 1, 10,  7])

### Upper Traingular Matrix

In [39]:
a = np.arange(1,10).reshape((3, 3))
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
np.triu(a)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

### Lower Traingular Matrix

In [41]:
a = np.arange(1,10).reshape((3, 3))
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [42]:
np.tril(a)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

### Transpose of Matrix

In [55]:
a = np.array([[1,4,5],[9,3,7]])
print("Original Array:\n",a)
print("Shape",a.shape)

Original Array:
 [[1 4 5]
 [9 3 7]]
Shape (2, 3)


In [56]:
b = a.transpose()
print("Transposed Array:\n",b)
print("Shape",b.shape)

Transposed Array:
 [[1 9]
 [4 3]
 [5 7]]
Shape (3, 2)
