## Matrix Operations

## Matrix Addition

Rule:
    
1. Both the matrix must be in same dimension (i.e) Same number of rows and columns

In [1]:
import numpy as np
m1 = np.array([[10,7,11],[8,6,20],[9,5,12]])
m2 = np.array([[6,4,1],[7,10,3],[2,15,7]])

In [2]:
print("First Matrix is\n", m1)
print("Second Matrix is\n", m2)

First Matrix is
 [[10  7 11]
 [ 8  6 20]
 [ 9  5 12]]
Second Matrix is
 [[ 6  4  1]
 [ 7 10  3]
 [ 2 15  7]]


In [3]:
print("Addition of two matrix =\n",m1+m2)

Addition of two matrix =
 [[16 11 12]
 [15 16 23]
 [11 20 19]]


## Matrix Subtraction

In [4]:
print("First Matrix is\n", m1)
print("Second Matrix is\n", m2)

First Matrix is
 [[10  7 11]
 [ 8  6 20]
 [ 9  5 12]]
Second Matrix is
 [[ 6  4  1]
 [ 7 10  3]
 [ 2 15  7]]


In [5]:
print("Subtraction of two matrix =\n", m1-m2)

Subtraction of two matrix =
 [[  4   3  10]
 [  1  -4  17]
 [  7 -10   5]]


## Assignment

Find the Matrix Addition of below mentioned matrix

In [6]:
m1 = np.array([[5,7],[9,8]])
m2 = np.array([[6,3,7],[7,4,6],[5,1,1]])

In [7]:
print("First Matrix is\n", m1)
print("Second Matrix is\n", m2)

First Matrix is
 [[5 7]
 [9 8]]
Second Matrix is
 [[6 3 7]
 [7 4 6]
 [5 1 1]]


In [8]:
print("Addition of two matrix =\n",m1+m2)

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

Note : In case if both the matrix of different shape(dimension) , then matrix addition or subtraction cant be performed

# Properties of Matrix Addition

## 1. Commutative Law

 A + B = B + A

In [9]:
A = np.array([[10,7,11],[8,6,20],[9,5,12]])
B = np.array([[6,4,1],[7,10,3],[2,15,7]])

In [10]:
print("Matrix A is\n", A)
print("Matrix B is\n", B)

Matrix A is
 [[10  7 11]
 [ 8  6 20]
 [ 9  5 12]]
Matrix B is
 [[ 6  4  1]
 [ 7 10  3]
 [ 2 15  7]]


In [11]:
print("Addition of A + B matrix =\n", A+B)

Addition of A + B matrix =
 [[16 11 12]
 [15 16 23]
 [11 20 19]]


In [12]:
print("Addition of B + A matrix =\n", B+A)

Addition of B + A matrix =
 [[16 11 12]
 [15 16 23]
 [11 20 19]]


## 2. Associative Law

A + ( B + C ) = (A + B) + C

In [13]:
A = np.array([[1,7],[8,5]])
B = np.array([[6,7],[5,10]])
C = np.array([[1,0],[6,11]])

In [14]:
print("Matrix A is\n", A)
print("Matrix B is\n", B)
print("Matrix C is\n", C)

Matrix A is
 [[1 7]
 [8 5]]
Matrix B is
 [[ 6  7]
 [ 5 10]]
Matrix C is
 [[ 1  0]
 [ 6 11]]


In [15]:
print("Addition of A + (B + C) matrix =\n", A+(B+C))

Addition of A + (B + C) matrix =
 [[ 8 14]
 [19 26]]


In [16]:
print("Addition of (A + B) + C matrix =\n", (A+B)+C)

Addition of (A + B) + C matrix =
 [[ 8 14]
 [19 26]]


## 3. Additive Identity

A + O = A

In [17]:
A = np.array([[6,7],[9,8]])
O = np.zeros((2,2),int)

In [18]:
print("Matrix A is\n", A)
print("Zero Matrix O is\n", O)

Matrix A is
 [[6 7]
 [9 8]]
Zero Matrix O is
 [[0 0]
 [0 0]]


In [19]:
print("Addition of A + O matrix =\n", A+O)

Addition of A + O matrix =
 [[6 7]
 [9 8]]


## 4. Additivie Inverse

A - A = 0

In [21]:
A = np.array([[6,7],[9,8]])

In [22]:
print("Matrix A is\n", A)

Matrix A is
 [[6 7]
 [9 8]]


In [23]:
print("Subtraction of A-A matrix =\n", A-A)

Subtraction of A-A matrix =
 [[0 0]
 [0 0]]


## Equality of a Matrix

Rule :
    
1. Both the matrix must be of same order

2. Correspoding elements in both the matrix must be same

In [24]:
A = np.array([[1,8],[9,4]])
B = np.array([[4,6],[9,7]])
C = np.array([[1,8],[9,4]])

In [25]:
print("Matrix A is\n", A)
print("Matrix B is\n", B)

Matrix A is
 [[1 8]
 [9 4]]
Matrix B is
 [[4 6]
 [9 7]]


In [26]:
# Both A and B are not same
print(A==B)

[[False False]
 [ True False]]


In [27]:
print("Matrix A is\n", A)
print("Matrix C is\n", C)

Matrix A is
 [[1 8]
 [9 4]]
Matrix C is
 [[1 8]
 [9 4]]


In [28]:
# Both A and C are same
print(A==C)

[[ True  True]
 [ True  True]]


# Matrix Multiplications

It can be done using two ways

1. By a Number ( Scalar Multiplication)

2. By an Another Matrix( Matrix Multiplication)

## 1. Scalar Multiplication

Multiplying every elements in the matrix by the same number(Scalar) to form a new matrix

In [29]:
A = 10
B = np.array([[10,20],[30,40]])

In [30]:
print("Scalar A is\n", A)
print("Matrix B is\n", B)

Scalar A is
 10
Matrix B is
 [[10 20]
 [30 40]]


In [31]:
print("Scalar Multiplication is \n", A*B)

Scalar Multiplication is 
 [[100 200]
 [300 400]]


## 2. Product of Matrix (or) Matrix Multiplication

Rule:

Number of columns in First Matrix = Number of rows in the Second Matrix

In [32]:
A = np.array([[10,20],[30,40]])
B = np.array([[7,1,3],[4,2,9]])

In [33]:
print("Matrix A is\n", A)
print("Matrix B is\n", B)

Matrix A is
 [[10 20]
 [30 40]]
Matrix B is
 [[7 1 3]
 [4 2 9]]


In [34]:
print("Matrix Multiplication is \n", A.dot(B))

Matrix Multiplication is 
 [[150  50 210]
 [370 110 450]]


Note: For matrix multiplication , dont use A*B , instead use A.dot(B)

## Assignment 

Perform Matrix Multiplication for the below matrix

In [35]:
A = np.array([[1,9],[3,4]])
B = np.array([[6,9],[5,2],[1,3]])

In [36]:
print("Matrix A is\n", A)
print("Matrix B is\n", B)

Matrix A is
 [[1 9]
 [3 4]]
Matrix B is
 [[6 9]
 [5 2]
 [1 3]]


In [37]:
print("Matrix Multiplication is \n", A.dot(B))

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

Conclusion : The number of columns in Matrix A is not equal to number of rows in Matrix B. Hence matrix multiplication can not be performed

# Properties of Matrix Multiplications

## 1. Commutative Property of Multiplication

(A * B) !=(Not Equal) (B * A)

In [38]:
A = np.array([[10,20,30],[30,40,50]])
B = np.array([[7,1],[4,2],[5,1]])

In [39]:
print("Matrix A is\n", A)
print("Matrix B is\n", B)

Matrix A is
 [[10 20 30]
 [30 40 50]]
Matrix B is
 [[7 1]
 [4 2]
 [5 1]]


In [40]:
print("Matrix Multiplication of A*B :\n", A.dot(B))

Matrix Multiplication of A*B :
 [[300  80]
 [620 160]]


In [41]:
print("Matrix Multiplication of B*A :\n", B.dot(A))

Matrix Multiplication of B*A :
 [[100 180 260]
 [100 160 220]
 [ 80 140 200]]


## 2. Multiplying with Identity Matrix

(A * I)  =  (I * A)

In [42]:
A = np.array([[1,3],[4,9]])
I = np.identity(2,int)

In [43]:
print("Matrix A is\n", A)
print("Identity Matrix I is\n", I)

Matrix A is
 [[1 3]
 [4 9]]
Identity Matrix I is
 [[1 0]
 [0 1]]


In [44]:
print("Matrix Multiplication of A*I :\n", A.dot(I))

Matrix Multiplication of A*I :
 [[1 3]
 [4 9]]


In [45]:
print("Matrix Multiplication of I*A :\n", I.dot(A))

Matrix Multiplication of I*A :
 [[1 3]
 [4 9]]
